name: CI

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  test-and-build:
    name: Test & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier format check
        run: npm run format:check

      - name: Run ESLint
        run: npm run lint
        continue-on-error: true # Known ESLint 9.x circular structure issue

      - name: Run TypeScript type check
        run: npx tsc --noEmit
        continue-on-error: true

      - name: Run unit tests with coverage
        run: npm run test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/coverage-final.json
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

      - name: Build application
        run: npm run build

      - name: Verify build
        run: |
          if [ ! -d ".next" ]; then
            echo "❌ Build failed - .next directory not created"
            exit 1
          fi
          echo "✅ Build succeeded"

      - name: Report build size
        run: |
          echo "### Build Output Size" >> $GITHUB_STEP_SUMMARY
          du -sh .next >> $GITHUB_STEP_SUMMARY
