name: Reseed Production Database

on:
  workflow_dispatch: # Manual trigger only
    inputs:
      confirmation:
        description: 'Type "RESEED PRODUCTION" to confirm'
        required: true
        type: string

jobs:
  reseed-production:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirmation == 'RESEED PRODUCTION'

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy with FORCE_RESEED=true
        run: |
          echo "🔄 Setting FORCE_RESEED=true and deploying..."
          gcloud run deploy lobbyist-registration \
            --region us-west1 \
            --update-env-vars FORCE_RESEED=true

      - name: Wait for deployment to complete
        run: |
          echo "⏳ Waiting 120 seconds for reseeding to complete..."
          sleep 120

      - name: Remove FORCE_RESEED flag
        run: |
          echo "🧹 Removing FORCE_RESEED flag..."
          gcloud run deploy lobbyist-registration \
            --region us-west1 \
            --remove-env-vars FORCE_RESEED

      - name: Success
        run: |
          echo "✅ Production database reseeded successfully!"
          echo "🌐 Application: https://lobbyist-registration-zzp44w3snq-uw.a.run.app"
